name: CI

on:
  pull_request:
  push:
    branches: ['master']
    tags: ['v*']
  schedule:
    - cron: '33 2 * * *'

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run make lint
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Hack around https://github.com/actions/checkout/issues/290
        run: |
          git fetch --tags --force

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@d4137dd840545b28521ed21931e06913d93c0bc1 # v1
        with:
          args: "--no-color -q"
          annotate: warning
